import os
from dotenv import load_dotenv

load_dotenv()
SALESFORCE_USERNAME = os.getenv("SALESFORCE_USERNAME")
SALESFORCE_PASSWORD = os.getenv("SALESFORCE_PASSWORD")
SALESFORCE_SECURITY_TOKEN = os.getenv("SALESFORCE_SECURITY_TOKEN")
INFLOW_BASE_URL = os.getenv("INFLOW_BASE_URL")
INFLOW_COMPANY_ID = os.getenv("INFLOW_COMPANY_ID")
INFLOW_TOKEN = os.getenv("INFLOW_TOKEN")
INFLOW_WEBHOOK_SUBSCRIPTION_ID = os.getenv("INFLOW_WEBHOOK_SUBSCRIPTION_ID")
SERVER_URL = os.getenv("SERVER_URL")
